# Generated by Django 5.0.4 on 2024-05-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadedfile_uploaded_by_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
