# Generated by Django 5.0.4 on 2024-05-08 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFile',
            new_name='UploadFiles',
        ),
    ]
